// <auto-generated />
using System;
using MVC_CodeFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCCodeFirst.Migrations
{
    [DbContext(typeof(DbSejm))]
    partial class DbSejmModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_CodeFirst.Models.Partia", b =>
                {
                    b.Property<int>("PartiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartiaId"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PartiaId");

                    b.ToTable("Partie");
                });

            modelBuilder.Entity("MVC_CodeFirst.Models.Posel", b =>
                {
                    b.Property<int>("PoselId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoselId"));

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartiaId")
                        .HasColumnType("int");

                    b.Property<int>("Wiek")
                        .HasColumnType("int");

                    b.HasKey("PoselId");

                    b.HasIndex("PartiaId");

                    b.ToTable("Poslowie");
                });

            modelBuilder.Entity("MVC_CodeFirst.Models.Posel", b =>
                {
                    b.HasOne("MVC_CodeFirst.Models.Partia", "Partia")
                        .WithMany("Poslowie")
                        .HasForeignKey("PartiaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Partia");
                });

            modelBuilder.Entity("MVC_CodeFirst.Models.Partia", b =>
                {
                    b.Navigation("Poslowie");
                });
#pragma warning restore 612, 618
        }
    }
}
