// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DbKraj))]
    [Migration("20221208193615_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Miasto", b =>
                {
                    b.Property<int>("MiastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MiastoId"));

                    b.Property<int>("IleMieszkancow")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("WojewodztwoId")
                        .HasColumnType("int");

                    b.HasKey("MiastoId");

                    b.HasIndex("WojewodztwoId");

                    b.ToTable("Miasta");
                });

            modelBuilder.Entity("WebApplication1.Models.Wojewodztwo", b =>
                {
                    b.Property<int>("WojewodzwoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WojewodzwoId"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WojewodzwoId");

                    b.ToTable("Wojewodztwa");
                });

            modelBuilder.Entity("WebApplication1.Models.Miasto", b =>
                {
                    b.HasOne("WebApplication1.Models.Wojewodztwo", "Wojewodztwo")
                        .WithMany("Miasta")
                        .HasForeignKey("WojewodztwoId");

                    b.Navigation("Wojewodztwo");
                });

            modelBuilder.Entity("WebApplication1.Models.Wojewodztwo", b =>
                {
                    b.Navigation("Miasta");
                });
#pragma warning restore 612, 618
        }
    }
}
